# # docker-compose.yml

# version: "3"

# services:
#   web:
#     build:
#       context: .
#       dockerfile: Dockerfile.dev
#     container_name: web
#     restart: always
#     volumes:
#       - ./:/app
#       - /app/node_modules
#       - /app/.next
#     ports:
#       - 3000:3000
version: "3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/app
      # - /app/node_modules
      # - /app/.next
    ports:
      - "3000:3000"
