import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import MainPageScroll from "../Components/MainPageScroll";
import { useRef, useEffect } from "react";

const Home: NextPage = () => {
  const wheelTimeout = useRef<any>();

  const onWheel = (e: any) => {
    clearTimeout(wheelTimeout.current);
    wheelTimeout.current = setTimeout(() => {
      wheelTimeout.current = false;
    }, 300);
  };

  // block the body from scrolling (or any other element)
  useEffect(() => {
    const cancelWheel = (e: any) => wheelTimeout.current && e.preventDefault();
    document.body.addEventListener("wheel", cancelWheel, { passive: false });
    return () => document.body.removeEventListener("wheel", cancelWheel);
  }, []);

  return (
    <div ref={wheelTimeout} className={styles.container}>
      <Head>
        <title>Logan Thomas</title>
        <meta name="description" content="Generated by Logan Thomas" />
        <link rel="icon" href="/logan-modified.png" />
      </Head>

      <main onWheel={(e) => {}} className={styles.main}>
        <MainPageScroll />
      </main>
    </div>
  );
};

export default Home;
