import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import MainPageScroll from "../Components/MainPageScroll";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Logan Thomas</title>
        <meta name="description" content="Generated by Logan Thomas" />
        <link rel="icon" href="/logan-modified.png" />
      </Head>

      <main className={styles.main}>
        <MainPageScroll />
      </main>
    </div>
  );
};

export default Home;
